### ISSUE TITLE
Tests currently failing (on my system)

### ISSUE THREAD

**Issue by pol** [davidbartonau/zbackup-tar#11] opened 2016-02-25 14:53 UTC
I tried running the tests:

```
[root@host zbackup-tar]# export PATH=$PATH:`pwd`
[root@host zbackup-tar]# cd tests
[root@host tests]# ./test.sh `pwd`/testdata
Executing Unit Tests in /mnt/lustrefs/backup/zbackup-tar/tests
rm: missing operand
Try `rm --help' for more information.
rm: missing operand
Try `rm --help' for more information.
mkdir: cannot create directory `/mnt/lustrefs/backup/zbackup-tar/tests/testdata/empty': File exists
mkdir: created directory `/tmp/zbackup-tar'
mkdir: created directory `/tmp/zbackup-tar//zbackup'
mkdir: created directory `/tmp/zbackup-tar//restored'
[UNIT TEST] ######## Backup 1 - Initial Backup ########
PREVBACKUP NEWBACKUP /tmp/zbackup-tar//zbackup/backups/backup01.tar
Specify either --password-file or --non-encrypted
empty   STORED
folder1 STORED
folder2 STORED
document.odt    STORED
document.pdf    STORED
funnyName"Quoted".txt,v STORED
funnyName'Quoted'.txt,v STORED
funnyName.txt,v STORED
folder1/subfolder1      STORED
folder1/subfolder2      STORED
folder1/delivery_area_TAS_locality_20nov2014.csv        STORED
folder1/subfolder1/1.jpg        STORED
folder1/subfolder1/2.jpeg       STORED
folder1/subfolder1/3.jpeg       STORED
folder1/subfolder1/4.JPG        STORED
folder1/subfolder1/5.gif        STORED
folder1/subfolder1/6.jpg        STORED
folder1/subfolder2/delivery_area_QLD_locality_20nov2014.csv     STORED
folder1/subfolder2/delivery_area_SA_locality_20nov2014.csv      STORED
folder2/logo.png        STORED
Traceback (most recent call last):
  File "/mnt/lustrefs/backup/zbackup-tar/zbackup-tar", line 418, in createZBackup
    tar.add (name = fullFile, arcname = nameInTar, recursive = False)
  File "/cm/shared/apps/python/3.4.3/lib/python3.4/tarfile.py", line 1923, in add
    self.addfile(tarinfo, f)
  File "/cm/shared/apps/python/3.4.3/lib/python3.4/tarfile.py", line 1952, in addfile
    copyfileobj(fileobj, self.fileobj, tarinfo.size)
  File "/cm/shared/apps/python/3.4.3/lib/python3.4/tarfile.py", line 242, in copyfileobj
    dst.write(buf)
  File "/cm/shared/apps/python/3.4.3/lib/python3.4/tarfile.py", line 433, in write
    self.__write(s)
  File "/cm/shared/apps/python/3.4.3/lib/python3.4/tarfile.py", line 441, in __write
    self.fileobj.write(self.buf[:self.bufsize])
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/lustrefs/backup/zbackup-tar/zbackup-tar", line 899, in <module>
    main()
  File "/mnt/lustrefs/backup/zbackup-tar/zbackup-tar", line 863, in main
    retCode = handleBackupCreation(cParser.parse_args())
  File "/mnt/lustrefs/backup/zbackup-tar/zbackup-tar", line 626, in handleBackupCreation
    createZBackup(nBackup, pArgs.aFlags)
  File "/mnt/lustrefs/backup/zbackup-tar/zbackup-tar", line 420, in createZBackup
    tar.close ()
  File "/cm/shared/apps/python/3.4.3/lib/python3.4/tarfile.py", line 2368, in __exit__
    self.fileobj.close()
  File "/cm/shared/apps/python/3.4.3/lib/python3.4/tarfile.py", line 455, in close
    self.fileobj.write(self.buf)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <bound method _Stream.__del__ of <tarfile._Stream object at 0x2aaab4f51c50>>
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.4.3/lib/python3.4/tarfile.py", line 409, in __del__
  File "/cm/shared/apps/python/3.4.3/lib/python3.4/tarfile.py", line 455, in close
ValueError: write to closed file
[UNIT TEST] FAIL zbackup-tar failed
```

**Comment by pol** [comment] 2016-02-25 14:55
Oh, some info:

zbackup version 1.4.1
uname -a: Linux host 2.6.32-431.29.2.el6.x86_64 #1 SMP Tue Sep 9 21:36:05 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
/etc/issue: CentOS release 6.7 (Final)

**Comment by davidbartonau** [comment] 2016-02-25 23:26
I think that the latest version of zbackup changed the parameters.  I am still using an old version of zbackup but I've been testing new versions as I want the new features.

The problem is this:
> Specify either --password-file or --non-encrypted

This should be an easy fix.  Let me look over the weekend.

**Comment by davidbartonau** [comment] 2016-02-28 04:48
I believe this is fixed now, can you please verify it works.  If it fails somewhere else, create a new issue.

**Comment by pol** [comment] 2016-02-29 16:16
It got farther this time, but now fails with:

```
diff: unrecognized option '--no-dereference'
diff: Try `diff --help' for more information.
[UNIT TEST] FAIL Restoring backup01.tar
```

Perhaps I am using an older version of diff than is expected?  The version that I have is: 

```
[root@hyalite tests]# diff --version
diff (GNU diffutils) 2.8.1
```

**Comment by pol** [comment] 2016-02-29 16:17
Sorry, I missed the second part of your message, I will create a new issue.

**Closed** 2016-02-29 23:40 UTC
